ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-NKUJKQ4\Scott];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

